### ISSUE TITLE
Bug: LR crashes with maximum exposure brush

### ISSUE THREAD

**Issue by conscienta** [jarnoh/knobroom#24]
Strange one. This image:

http://www.rossharveyweddings.com/images/5423.jpg

Will crash LR if selected with KR running. Turn KR off, and it's fine.

Background was brushed with maximum exposure, highlights and shadows.

Happened on a few images of this style.

OSX 10.6.8, BCR2000 (Firmware 1.1)

**Comment by jarnoh** [comment]
I managed to reproduce issue using this preset: http://www.capturemonkey.com/experimental-noise-texture-layer-for-lightroom

Since there currently is no real use to pass brush data to the MIDI server, I'm disabling sending PaintBasedCorrections from the plugin, and hoping to release a new build soon (I've disabled automatic building for few days ;)

**Comment by conscienta** [comment]
Fingers crossed! Look forward to the next release :)
